# Generated by Django 5.2.4 on 2025-09-27 07:54

from django.db import migrations


def update_is_active(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.is_active = user.status == 'Activo'
        user.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_departamento'),
    ]

    operations = [
        migrations.RunPython(update_is_active),
    ]
