# Generated by Django 5.2.4 on 2025-10-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/', verbose_name='Documento PDF'),
        ),
    ]
