# Generated by Django 5.2.4 on 2025-09-30 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('masterdata', '0001_initial'), ('masterdata', '0002_tipoactivo'), ('masterdata', '0003_marca'), ('masterdata', '0004_alter_marca_options_alter_marca_name'), ('masterdata', '0005_modelo_especificacionescomputo_and_more'), ('masterdata', '0006_remove_especificacionesred_modelo_and_more'), ('masterdata', '0007_remove_modelocomputo_marca_and_more'), ('masterdata', '0008_alter_modeloactivo_puertos_ethernet_auditlog')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fincas', to='masterdata.region')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Área')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='masterdata.departamento', verbose_name='Departamento al que pertenece')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['name'],
                'unique_together': {('name', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activos',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='ModeloActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procesador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Procesador')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)')),
                ('almacenamiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Almacenamiento')),
                ('tarjeta_grafica', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tarjeta Gráfica')),
                ('wifi', models.BooleanField(default=False, verbose_name='WIFI')),
                ('ethernet', models.BooleanField(default=False, verbose_name='Ethernet')),
                ('puertos_ethernet', models.CharField(blank=True, choices=[('1', '1 puerto'), ('4', '4 puertos'), ('8', '8 puertos'), ('16', '16 puertos'), ('24', '24 puertos'), ('48', '48 puertos')], max_length=50, null=True, verbose_name='Puertos Ethernet')),
                ('puertos_sfp', models.CharField(blank=True, choices=[('0', '0 puertos'), ('2', '2 puertos'), ('4', '4 puertos'), ('8', '8 puertos')], max_length=50, null=True, verbose_name='Puertos SFP')),
                ('puerto_consola', models.BooleanField(default=False, verbose_name='Puerto Consola')),
                ('puertos_poe', models.CharField(blank=True, choices=[('0', '0 puertos'), ('4', '4 puertos'), ('8', '8 puertos'), ('16', '16 puertos'), ('24', '24 puertos'), ('48', '48 puertos')], max_length=50, null=True, verbose_name='Puertos PoE')),
                ('alimentacion', models.CharField(blank=True, choices=[('AC', 'AC'), ('Transformador', 'Transformador'), ('PoE', 'PoE')], max_length=50, null=True, verbose_name='Alimentación')),
                ('administrable', models.BooleanField(default=False, verbose_name='Administrable')),
                ('tamano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamaño')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('conectores', models.TextField(blank=True, null=True, verbose_name='Conectores')),
                ('cables', models.TextField(blank=True, null=True, verbose_name='Cables')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_activo', to='masterdata.marca', verbose_name='Marca')),
                ('tipo_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_activo', to='masterdata.tipoactivo', verbose_name='Tipo de Activo')),
            ],
            options={
                'verbose_name': 'Modelo de Activo',
                'verbose_name_plural': 'Modelos de Activo',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='modeloactivo',
            name='puertos_ethernet',
            field=models.CharField(blank=True, choices=[('1', '1 puerto'), ('4', '4 puertos'), ('8', '8 puertos'), ('16', '16 puertos'), ('24', '24 puertos'), ('48', '48 puertos')], max_length=50, null=True, verbose_name='Puertos Ethernet'),
        ),
    ]
