# Generated by Django 5.2.4 on 2025-09-27 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_remove_especificacionesred_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelocomputo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='modelocomputo',
            name='tipo_activo',
        ),
        migrations.CreateModel(
            name='ModeloActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procesador', models.CharField(blank=True, max_length=150, null=True, verbose_name='Procesador')),
                ('ram', models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)')),
                ('almacenamiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Almacenamiento')),
                ('tarjeta_grafica', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tarjeta Gráfica')),
                ('wifi', models.BooleanField(default=False, verbose_name='WIFI')),
                ('ethernet', models.BooleanField(default=False, verbose_name='Ethernet')),
                ('puertos_ethernet', models.CharField(blank=True, choices=[('4', '4 puertos'), ('8', '8 puertos'), ('16', '16 puertos'), ('24', '24 puertos'), ('48', '48 puertos')], max_length=50, null=True, verbose_name='Puertos Ethernet')),
                ('puertos_sfp', models.CharField(blank=True, choices=[('0', '0 puertos'), ('2', '2 puertos'), ('4', '4 puertos'), ('8', '8 puertos')], max_length=50, null=True, verbose_name='Puertos SFP')),
                ('puerto_consola', models.BooleanField(default=False, verbose_name='Puerto Consola')),
                ('puertos_poe', models.CharField(blank=True, choices=[('0', '0 puertos'), ('4', '4 puertos'), ('8', '8 puertos'), ('16', '16 puertos'), ('24', '24 puertos'), ('48', '48 puertos')], max_length=50, null=True, verbose_name='Puertos PoE')),
                ('alimentacion', models.CharField(blank=True, choices=[('AC', 'AC'), ('Transformador', 'Transformador'), ('PoE', 'PoE')], max_length=50, null=True, verbose_name='Alimentación')),
                ('administrable', models.BooleanField(default=False, verbose_name='Administrable')),
                ('tamano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamaño')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Color')),
                ('conectores', models.TextField(blank=True, null=True, verbose_name='Conectores')),
                ('cables', models.TextField(blank=True, null=True, verbose_name='Cables')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_activo', to='masterdata.marca', verbose_name='Marca')),
                ('tipo_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_activo', to='masterdata.tipoactivo', verbose_name='Tipo de Activo')),
            ],
            options={
                'verbose_name': 'Modelo de Activo',
                'verbose_name_plural': 'Modelos de Activo',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='EspecificacionesComputo',
        ),
        migrations.DeleteModel(
            name='ModeloComputo',
        ),
    ]
