# Generated by Django 5.2.4 on 2025-09-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial_squashed_0009_auditlog_new_data_auditlog_old_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('nombre_contacto', models.CharField(max_length=255, verbose_name='Nombre de Contacto')),
                ('telefono_ventas', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Ventas')),
                ('correo_ventas', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Ventas')),
                ('telefono_soporte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Soporte')),
                ('correo_soporte', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Soporte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
    ]
