# Generated by Django 5.2.4 on 2025-09-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0011_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
