# Generated by Django 5.2.4 on 2025-10-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0014_alter_modeloactivo_alimentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='activity_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('RETIRE', 'Retire'), ('REACTIVATE', 'Reactivate'), ('RETURN', 'Return')], max_length=20),
        ),
    ]
