# Generated by Django 5.2.4 on 2025-09-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_activo_costo_activo_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Orden de Compra'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='solicitante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitante'),
        ),
    ]
