# Generated by Django 5.2.4 on 2025-09-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_activo_correo_electronico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
