# Generated by Django 5.2.4 on 2025-10-01 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_activo_motivo_baja_activo_usuario_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='activo',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AddField(
            model_name='activo',
            name='usuario_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_retirados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que dio de Baja'),
        ),
    ]
