# Generated by Django 5.2.4 on 2025-10-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='documentos_baja',
            field=models.JSONField(blank=True, help_text='Lista de rutas de archivos subidos al dar de baja el activo', null=True, verbose_name='Documentos de Baja'),
        ),
    ]
