# Generated by Django 5.2.4 on 2025-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_maintenance_options_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='administrable',
            field=models.BooleanField(default=False, verbose_name='Administrable'),
        ),
        migrations.AddField(
            model_name='activo',
            name='alimentacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alimentación'),
        ),
        migrations.AddField(
            model_name='activo',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Almacenamiento'),
        ),
        migrations.AddField(
            model_name='activo',
            name='cables',
            field=models.TextField(blank=True, null=True, verbose_name='Cables'),
        ),
        migrations.AddField(
            model_name='activo',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='activo',
            name='conectores',
            field=models.TextField(blank=True, null=True, verbose_name='Conectores'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ethernet',
            field=models.BooleanField(default=False, verbose_name='Ethernet'),
        ),
        migrations.AddField(
            model_name='activo',
            name='procesador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='activo',
            name='puerto_consola',
            field=models.BooleanField(default=False, verbose_name='Puerto Consola'),
        ),
        migrations.AddField(
            model_name='activo',
            name='puertos_ethernet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puertos Ethernet'),
        ),
        migrations.AddField(
            model_name='activo',
            name='puertos_poe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puertos PoE'),
        ),
        migrations.AddField(
            model_name='activo',
            name='puertos_sfp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puertos SFP'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tamano',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tarjeta_grafica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tarjeta Gráfica'),
        ),
        migrations.AddField(
            model_name='activo',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='WIFI'),
        ),
    ]
