# Generated by Django 5.2.4 on 2025-10-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_activo_administrable_activo_alimentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='administrable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Administrable'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ethernet',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ethernet'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='puerto_consola',
            field=models.BooleanField(blank=True, null=True, verbose_name='Puerto Consola'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='wifi',
            field=models.BooleanField(blank=True, null=True, verbose_name='WIFI'),
        ),
    ]
