# Generated by Django 5.2.4 on 2025-10-07 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_set_boolean_fields_to_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Usuario al que está asignado este activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
    ]
