"""
Django settings for itam_backend project.

Este archivo contiene toda la configuración del proyecto Django ITAM.
Aquí se definen:
- Aplicaciones instaladas (INSTALLED_APPS)
- Configuración de base de datos MySQL
- Configuración de autenticación JWT
- Configuración de CORS para el frontend React
- Configuración de archivos estáticos y media
- Y otras configuraciones del sistema

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os 
from pathlib import Path
from datetime import timedelta
from decouple import config 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =  config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['35.222.196.157', '127.0.0.1', 'localhost', '10.10.24.63', '10.10.240.164']


# Application definition
# Lista de aplicaciones Django instaladas y activas en el proyecto
# Incluye las aplicaciones del sistema ITAM: users, masterdata, assets, employees

INSTALLED_APPS = [
    'django.contrib.admin',        # Panel de administración de Django
    'django.contrib.auth',         # Sistema de autenticación de Django
    'django.contrib.contenttypes', # Framework de tipos de contenido
    'django.contrib.sessions',     # Manejo de sesiones de usuario
    'django.contrib.messages',     # Sistema de mensajes
    'django.contrib.staticfiles',  # Manejo de archivos estáticos
    'apps.users',                  # Aplicación de gestión de usuarios personalizada
    'rest_framework',              # Django REST Framework para APIs
    'rest_framework_simplejwt',    # Autenticación JWT para APIs
    'corsheaders',                 # Manejo de CORS para frontend
    'django_filters',              # Filtros avanzados para APIs
    'apps.masterdata',             # Datos maestros (regiones, tipos, marcas, etc.)
    'apps.assets',                 # Gestión de activos tecnológicos
    'apps.employees',              # Gestión de empleados
]

AUTH_USER_MODEL = 'users.CustomUser'  # Modelo de usuario personalizado - ¡CRÍTICO!
# Reemplaza el modelo User por defecto de Django con nuestro CustomUser
# que incluye campos adicionales como departamento, región, puesto, etc.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',           # Seguridad básica de Django
    'corsheaders.middleware.CorsMiddleware',                   # Manejo de CORS para frontend React
    'django.contrib.sessions.middleware.SessionMiddleware',    # Manejo de sesiones HTTP
    'django.middleware.common.CommonMiddleware',               # Middleware común (URLs, etc.)
    'django.middleware.csrf.CsrfViewMiddleware',               # Protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Autenticación de usuarios
    'middleware.CurrentUserMiddleware',                        # Middleware personalizado para usuario actual
    'django.contrib.messages.middleware.MessageMiddleware',    # Sistema de mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protección contra clickjacking
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# Configuración de la base de datos MySQL
# Las credenciales se obtienen de variables de entorno usando python-decouple
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',        # Motor de base de datos MySQL
        'NAME': config('DB_NAME'),                   # Nombre de la base de datos
        'USER': config('DB_USER'),                   # Usuario de MySQL
        'PASSWORD': config('DB_PASSWORD'),           # Contraseña de MySQL
        'HOST': config('DB_HOST'),                   # Host del servidor MySQL
        'PORT': config('DB_PORT'),                   # Puerto de MySQL (normalmente 3306)
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'staticfiles')

# Media files (uploaded files)
MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR.parent / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de Django REST Framework
# Define cómo funcionan las APIs del sistema

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Autenticación JWT para todas las APIs
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        #'rest_framework.permissions.IsAuthenticated',  # Requeriría autenticación para todas las APIs
        'rest_framework.permissions.AllowAny',  # Permite acceso público (útil para desarrollo)
    )
}

# Configuración de JWT (JSON Web Tokens) para autenticación
# Los tokens permiten mantener sesiones de usuario sin estado en el servidor

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Token de acceso dura 15 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Token de refresco dura 7 días
    'ROTATE_REFRESH_TOKENS': False,                  # No rotar tokens automáticamente
    'BLACKLIST_AFTER_ROTATION': True,                # Invalidar tokens anteriores
    'UPDATE_LAST_LOGIN': False,                      # No actualizar fecha de último login

    'ALGORITHM': 'HS256',                            # Algoritmo de encriptación
    'SIGNING_KEY': 'django-insecure-v^2u)3-%-0vsy75g0bbafaqj&7g0nxg6dsbr(t$ue7bkta6ike',  # ¡CLAVE SECRETA!
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),                # Tipo de header para tokens
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',        # Nombre del header HTTP
    'USER_ID_FIELD': 'id',                           # Campo ID del usuario
    'USER_ID_CLAIM': 'user_id',                      # Claim en el token
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Configuración de CORS (Cross-Origin Resource Sharing)
# Permite que el frontend React se comunique con el backend Django
# Lista de orígenes permitidos para hacer peticiones al API

CORS_ALLOWED_ORIGINS = [
    "http://35.222.196.157",    # IP del servidor en producción
    "https://35.222.196.157",   # IP del servidor con HTTPS
    "http://localhost:3000",     # Desarrollo local - puerto estándar de React
    "http://127.0.0.1:3000",     # Desarrollo local - localhost alternativo
    "http://10.10.24.63:3000",   # IP específica de la red local
    "http://10.10.240.164:3000", # Otra IP de la red local
]

# También puedes usar CORS_ALLOW_ALL_ORIGINS = True para desarrollo
# Pero es mejor ser específico con CORS_ALLOWED_ORIGINS en producción.
# CORS_ALLOW_ALL_ORIGINS = True # <-- Puedes descomentar esto para pruebas rápidas, pero no para producción

# Métodos HTTP permitidos en las peticiones CORS
CORS_ALLOW_METHODS = [
    'DELETE',   # Eliminar recursos
    'GET',      # Obtener datos
    'OPTIONS',  # Preflight requests
    'PATCH',    # Actualizaciones parciales
    'POST',     # Crear nuevos recursos
    'PUT',      # Actualizaciones completas
]

# Headers HTTP permitidos en las peticiones CORS
CORS_ALLOW_HEADERS = [
    'accept',           # Tipo de contenido aceptado
    'accept-encoding',  # Codificación aceptada
    'authorization',    # Header para tokens JWT
    'content-type',     # Tipo de contenido del body
    'dnt',             # Do Not Track
    'origin',          # Origen de la petición
    'user-agent',      # Información del navegador
    'x-csrftoken',     # Token CSRF de Django
    'x-requested-with', # Indica petición AJAX
]
