# Generated by Django 5.2.4 on 2025-09-26 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_alter_marca_options_alter_marca_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Modelo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción General')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='masterdata.marca', verbose_name='Marca')),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='masterdata.tipoactivo', verbose_name='Tipo de Activo')),
            ],
            options={
                'verbose_name': 'Modelo de Activo',
                'verbose_name_plural': 'Modelos de Activo',
                'ordering': ['name'],
                'unique_together': {('name', 'marca', 'tipo_activo')},
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesComputo',
            fields=[
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spec_computo', serialize=False, to='masterdata.modelo')),
                ('procesador', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50, verbose_name='RAM (Ej: 8GB DDR4)')),
                ('almacenamiento', models.CharField(max_length=100, verbose_name='Almacenamiento (Ej: 256GB SSD)')),
                ('tarjeta_grafica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta Gráfica (Opcional)')),
                ('wifi', models.BooleanField(default=False, verbose_name='Conectividad WiFi')),
                ('ethernet', models.BooleanField(default=True, verbose_name='Conectividad Ethernet')),
            ],
            options={
                'verbose_name': 'Especificación de Cómputo',
                'verbose_name_plural': 'Especificaciones de Cómputo',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesPeriferico',
            fields=[
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spec_periferico', serialize=False, to='masterdata.modelo')),
                ('tamano', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamaño / Dimensiones')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('conectores', models.CharField(max_length=255, verbose_name='Conectores (Ej: USB, HDMI, Jack 3.5mm)')),
                ('cables', models.CharField(max_length=255, verbose_name='Cables Incluidos (Ej: USB-A, HDMI)')),
            ],
            options={
                'verbose_name': 'Especificación de Periférico',
                'verbose_name_plural': 'Especificaciones de Periféricos',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesRed',
            fields=[
                ('modelo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spec_red', serialize=False, to='masterdata.modelo')),
                ('puertos_ethernet', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48')], default=8, verbose_name='Puertos Ethernet')),
                ('puertos_sfp', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=0, verbose_name='Puertos SFP')),
                ('puerto_consola', models.BooleanField(default=False, verbose_name='Puerto Consola (Sí/No)')),
                ('puertos_poe', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48')], default=0, verbose_name='Puertos PoE')),
                ('alimentacion', models.CharField(choices=[('AC', 'Corriente Alterna (AC)'), ('Transformador', 'Transformador Externo'), ('PoE', 'Power over Ethernet (PoE)')], default='AC', max_length=20, verbose_name='Alimentación')),
                ('administrable', models.BooleanField(default=False, verbose_name='Administrable (Sí/No)')),
            ],
            options={
                'verbose_name': 'Especificación de Red',
                'verbose_name_plural': 'Especificaciones de Red',
            },
        ),
    ]
