# Generated by Django 5.2.4 on 2025-09-27 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_modelo_especificacionescomputo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesred',
            name='modelo',
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='tipo_activo',
        ),
        migrations.RemoveField(
            model_name='especificacionescomputo',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='especificacionescomputo',
            name='ethernet',
        ),
        migrations.RemoveField(
            model_name='especificacionescomputo',
            name='tarjeta_grafica',
        ),
        migrations.RemoveField(
            model_name='especificacionescomputo',
            name='wifi',
        ),
        migrations.AddField(
            model_name='especificacionescomputo',
            name='almacenamiento_capacidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad Almacenamiento (GB)'),
        ),
        migrations.AddField(
            model_name='especificacionescomputo',
            name='almacenamiento_tipo',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD')], default='SSD', max_length=50),
        ),
        migrations.AlterField(
            model_name='especificacionescomputo',
            name='procesador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionescomputo',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='Memoria RAM (GB)'),
        ),
        migrations.CreateModel(
            name='ModeloComputo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Modelo')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Especificaciones Técnicas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos_computo', to='masterdata.marca', verbose_name='Marca')),
                ('tipo_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_computo', to='masterdata.tipoactivo', verbose_name='Tipo de Activo')),
            ],
            options={
                'verbose_name': 'Modelo de Cómputo',
                'verbose_name_plural': 'Modelos de Cómputo',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='especificacionescomputo',
            name='modelo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='especificaciones', serialize=False, to='masterdata.modelocomputo'),
        ),
        migrations.DeleteModel(
            name='EspecificacionesPeriferico',
        ),
        migrations.DeleteModel(
            name='EspecificacionesRed',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
