# Generated by Django 5.2.4 on 2025-09-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_alter_modeloactivo_puertos_ethernet_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores'),
        ),
    ]
