# Generated by Django 5.2.4 on 2025-10-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_create_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloactivo',
            name='alimentacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alimentación'),
        ),
        migrations.AlterField(
            model_name='modeloactivo',
            name='puertos_ethernet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puertos Ethernet'),
        ),
        migrations.AlterField(
            model_name='modeloactivo',
            name='puertos_poe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puertos PoE'),
        ),
        migrations.AlterField(
            model_name='modeloactivo',
            name='puertos_sfp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puertos SFP'),
        ),
    ]
