# Generated by Django 5.2.4 on 2025-09-27 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0012_delete_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=255, unique=True, verbose_name='Serie')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='Hostname')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('fecha_fin_garantia', models.DateField(verbose_name='Fecha de Fin de Garantía')),
                ('solicitante', models.CharField(max_length=255, verbose_name='Solicitante')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('orden_compra', models.CharField(max_length=255, verbose_name='Orden de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.area', verbose_name='Área')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.departamento', verbose_name='Departamento')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.finca', verbose_name='Finca')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.modeloactivo', verbose_name='Modelo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.proveedor', verbose_name='Proveedor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.region', verbose_name='Región')),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='masterdata.tipoactivo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['-created_at'],
            },
        ),
    ]
