# Generated by Django 5.2.4 on 2025-09-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='cuenta_contable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cuenta Contable'),
        ),
        migrations.AddField(
            model_name='activo',
            name='cuotas',
            field=models.IntegerField(blank=True, choices=[(1, '1 mes'), (3, '3 meses'), (6, '6 meses'), (12, '12 meses'), (18, '18 meses'), (24, '24 meses'), (36, '36 meses'), (48, '48 meses'), (60, '60 meses')], null=True, verbose_name='Cuotas'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo_costo',
            field=models.CharField(blank=True, choices=[('costo', 'Costo'), ('mensualidad', 'Mensualidad')], max_length=20, null=True, verbose_name='Tipo de Costo'),
        ),
    ]
