# Generated by Django 5.2.4 on 2025-09-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_activo_cuenta_contable_activo_cuotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='moneda',
            field=models.CharField(blank=True, choices=[('USD', 'Dólares'), ('GTQ', 'Quetzales')], max_length=3, null=True, verbose_name='Moneda'),
        ),
    ]
