# Generated by Django 5.2.4 on 2025-09-28 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_activo_estado_activo_fecha_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AddField(
            model_name='activo',
            name='usuario_baja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_retirados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que dio de Baja'),
        ),
    ]
