# Generated by Django 5.2.4 on 2025-10-01 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_activo_documentos_baja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='proximo_mantenimiento',
            field=models.DateField(blank=True, help_text='Fecha calculada para el próximo mantenimiento', null=True, verbose_name='Próximo Mantenimiento'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tecnico_mantenimiento',
            field=models.ForeignKey(blank=True, help_text='Último técnico que realizó mantenimiento a este activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico de Mantenimiento'),
        ),
        migrations.AddField(
            model_name='activo',
            name='ultimo_mantenimiento',
            field=models.DateField(blank=True, help_text='Fecha del último mantenimiento realizado', null=True, verbose_name='Último Mantenimiento'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('findings', models.TextField(help_text='Descripción de los hallazgos encontrados durante el mantenimiento', verbose_name='Hallazgos')),
                ('next_maintenance_date', models.DateField(help_text='Fecha calculada para el próximo mantenimiento', verbose_name='Próximo Mantenimiento')),
                ('attachments', models.JSONField(blank=True, help_text='Lista de rutas de archivos subidos durante el mantenimiento', null=True, verbose_name='Archivos Adjuntos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.activo', verbose_name='Activo')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico que realizó el mantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
