# Generated by Django 5.2.4 on 2025-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_activo_proximo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-maintenance_date', '-id'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AddField(
            model_name='activo',
            name='ultimo_mantenimiento_hallazgos',
            field=models.TextField(blank=True, help_text='Hallazgos del último mantenimiento realizado', null=True, verbose_name='Últimos Hallazgos de Mantenimiento'),
        ),
    ]
