# Generated by Django 5.2.4 on 2025-10-05 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_maintenance_options_and_more'),
        ('employees', '0002_employee_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assets.activo', verbose_name='Activo')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.employee', verbose_name='Empleado')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_returned', to=settings.AUTH_USER_MODEL, verbose_name='Devuelto por')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-assigned_date'],
                'unique_together': {('activo', 'employee', 'assigned_date')},
            },
        ),
    ]
