# Generated by Django 5.2.4 on 2025-10-06 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_activo_administrable_alter_activo_ethernet_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE assets_activo
            SET wifi = NULL, ethernet = NULL, puerto_consola = NULL, administrable = NULL
            WHERE wifi = 0 AND ethernet = 0 AND puerto_consola = 0 AND administrable = 0;
            """,
            reverse_sql="""
            UPDATE assets_activo
            SET wifi = 0, ethernet = 0, puerto_consola = 0, administrable = 0
            WHERE wifi IS NULL AND ethernet IS NULL AND puerto_consola IS NULL AND administrable IS NULL;
            """
        ),
    ]
